# NovaOS User Configuration

# Default username
defaultUserName: nova

# Default groups
defaultGroups:
  - users
  - wheel
  - audio
  - video
  - storage
  - network
  - games
  - input
  - lp

# Hostname
hostName: novaos-pc

# Auto-login
autoLogin: false

# Root account
doRootAccount: true
rootPassword: ""
rootPasswordHint: "Leave empty for no root password (sudo via wheel group)"

# Password requirements
passwordRequirements:
  nonempty: true
  minLength: 1
  maxLength: -1
  checkStrength: false

# User shell
defaultShell: /bin/bash
