title NovaOS
linux /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd /%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
options boot=%INSTALL_DIR% archisobasedir=%INSTALL_DIR% archisodevice=archisolabel=%ISO_LABEL%
